language: python
python:
- '2.7'
install:
- sudo apt-get install -y curl tar
- curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sudo sh
- pip install -r functions/convert/requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls
script: coverage run setup.py test
after_success:
- coveralls
- pip install -r functions/convert/requirements.txt -t functions/convert/
deploy:
- provider: script
  skip_cleanup: true
  script: "apex deploy --env $TRAVIS_BRANCH"
  on:
    branch:
    - develop
    - master
    python: '2.7'
env:
  global:
  - AWS_REGION=$(eval echo \$${TRAVIS_BRANCH}_aws_region)
  - AWS_ACCESS_KEY_ID=$(eval echo \$${TRAVIS_BRANCH}_aws_access_key_id)
  - AWS_SECRET_ACCESS_KEY=$(eval echo \$${TRAVIS_BRANCH}_aws_secret_access_key)
